# Generated by Django 4.1.5 on 2023-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(help_text='Изображение должно быть в формате jpg или png и разрешением больше FullHD', upload_to='images/', verbose_name='Изображение')),
                ('middle_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок второго блока (необязательно)')),
                ('middle_body', models.TextField(blank=True, null=True, verbose_name='Текст второго блока (необязательно)')),
                ('middle_image', models.ImageField(blank=True, help_text='Изображение должно быть в формате jpg или png и разрешением больше FullHD', null=True, upload_to='images/', verbose_name='Изображение второго блока (необязательно)')),
                ('last_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок третьего блока (необязательно)')),
                ('last_body', models.TextField(blank=True, null=True, verbose_name='Текст третьего блока (необязательно)')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(help_text='Уникальное значение для URL. Используйте только латинские символы, цифры, дефисы и знаки подчеркивания.', max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-pub_date'],
            },
        ),
    ]
